#include <stdio.h>
#include <stdlib.h>
#include "sqlite3.h"

/*
Q5 15pts

The goal of this question is to quantify the impact (if any) of the built-in 
R-Tree module in SQLite. To do so, build standard SQlite indexes on each of 
the individual Cartesian coordinates of the POIs.

Write a C program, in a file called q5.c that:

    1. Generates 100 randomly chosen bounding squares with side of 
    length l, read as a parameter to the program. The coordinates 
    of the square should be generated by your program.

    2. Computes the average time (out of 20 runs for each query rectangle) 
    to find the total number of objects in that square, using the R-Tree
    and using the standard SQLite indexes (only).
    
    3. Prints the average times for each scenario after all runs.

The output of the program should look like this:

Parameter l: ...

Average runtime with r-tree: ... ms

Average runtime without r-tree: ... ms

*/

int main(int argc, char **argv)
{
	  sqlite3 *db; //the database
	  sqlite3_stmt *stmt; //the select statement

  	int rc;

  	if( argc!=2 )
    {
    	  fprintf(stderr, "Usage: %s <database file>\n", argv[0]);
    	  return(1);
  	}

  	rc = sqlite3_open(argv[1], &db);
  	if( rc )
    {
      	fprintf(stderr, "Can't open database: %s\n", sqlite3_errmsg(db));
      	sqlite3_close(db);
      	return(1);
  	}


    // This select is to check to see if the lat,lon have been projected or not.
    //char *sql_select = "select lat,lon from poi limit 1";

    // This SQL statement updates the lat and lon to their projected values on a 1000,1000 grid
    char *sql_stmt = "update poi " \
                      "set lat=((((lat - 48.06000) * (1000 - 0)) / (48.24900 - 48.06000)) + 0), " \
                      "lon=((((lon - 11.35800) * (1000 - 0)) / (11.72400 - 11.35800)) + 0);";

  	rc = sqlite3_prepare_v2(db, sql_stmt, -1, &stmt, 0);

    if (rc != SQLITE_OK) 
    {  
        fprintf(stderr, "Preparation failed: %s\n", sqlite3_errmsg(db));
        sqlite3_close(db);
        return 1;
    }    

    while((rc = sqlite3_step(stmt)) == SQLITE_ROW) { }

    sqlite3_finalize(stmt); //always finalize a statement

    return 0;
}
